-- AlterTable
ALTER TABLE `Roles_has_permissions` MODIFY `assignAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `User` MODIFY `created_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updated_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `Users_has_roles` MODIFY `assignedAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3);
